### create an option
POST http://localhost:3000/options/create
Content-Type: application/json

{
  "question_id": "ffc51a03-ec2e-4704-ab24-2843c2a4559f",
  "option_text":"Quiz-1_question-4_op-3",
  "is_correct": false
}

### update an existing option
PATCH http://localhost:3000/options/b800abc9-099c-4865-9a27-343f2c4add8e
Content-Type: application/json

{
  "option_text":"updated option",
  "is_correct": false
}

### Delete an existing option
DELETE http://localhost:3000/options/7373698a-c703-4889-835a-4aadb3d7f5df

### Fetch all options
GET  http://localhost:3000/options
