### create new question
POST http://localhost:3000/questions/create
Content-Type: application/json

{
  "quiz_id":"a60200b2-2e19-4f5f-b64f-ededda7a27fe",
  "question_text": "Quiz_1_Question_5",
  "question_type":"multiple_choice"
}

### Fetch all question for existing quiz id
GET http://localhost:3000/questions/a60200b2-2e19-4f5f-b64f-ededda7a27fe
### Update question by id
PATCH http://localhost:3000/questions/bb1549b6-1dca-4af3-b296-ecd5de15d75c
Content-Type: application/json

{
  "question_text": "what is your faveret color!?"
}

### Delete quiz by id
DELETE http://localhost:3000/questions/bb56ca17-8b53-4069-9f88-b4642e206145
