### Create a new user 
POST http://localhost:3000/users/create
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZjYjBjZGEyLWJlMGEtNDhmYy1hOWVmLTQyOGFmNDljOWYzZSIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3MjU4ODk3ODIsImV4cCI6MTcyNTk3NjE4Mn0.aaSL_79de-KM87J-4DkeNsIkfJdP9FiARoaaI6CSckA
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlNTBlN2M5LTE0NDQtNGUxMC1iYjIzLTQwOWNlYzYyZmIzNSIsInVzZXJuYW1lIjoidGVzdDIiLCJpYXQiOjE3MjU4ODk3ODksImV4cCI6MTcyNTk3NjE4OX0.cFIxD-RwEVkO6GjUZj0GdbpSuSdc_OyxSi9w_H9QcPA
# Authorization: Bearer InvalidToken---yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlNTBlN2M5LTE0NDQtNGUxMC1iYjIzLTQwOWNlYzYyZmIzNSIsInVzZXJuYW1lIjoidGVzdDIiLCJpYXQiOjE3MjU4ODc1OTAsImV4cCI6MTcyNTg5MTE5MH0.M8DPMH0pdLDDl4bzFw8sBh-DKQMH2_0eRWF6okFJkH0
Content-Type: application/json

{
  "username": "test5",
  "email"   : "test5@email.com",
  "password": "123456"
}

### Update user by id
PATCH http://localhost:3000/users/b9250261-644b-401f-8cc5-628e42499f8d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZjYjBjZGEyLWJlMGEtNDhmYy1hOWVmLTQyOGFmNDljOWYzZSIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3MjU4ODU0NjYsImV4cCI6MTcyNTg4OTA2Nn0.HNFgS5Sh-5ZvYCcsKKYcd_DwZaABuwe3rcGPj7MSsOw
Content-Type: application/json

{
  "username": "test_updated_2",
  "password": "start"
}
### delete user by id
DELETE http://localhost:3000/users/44dcfb86-feee-4b5d-8ab3-ec8c6bf4fca2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZjYjBjZGEyLWJlMGEtNDhmYy1hOWVmLTQyOGFmNDljOWYzZSIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3MjU4ODU0NjYsImV4cCI6MTcyNTg4OTA2Nn0.HNFgS5Sh-5ZvYCcsKKYcd_DwZaABuwe3rcGPj7MSsOw

# ###  login to an admin user
# POST http://localhost:3000/users/signin
# Content-Type: application/json

# {
#   "email"   : "admin@example.com",
#   "password": "admin"
# }

### login to exist user
# POST http://localhost:3000/users/signin
# Content-Type: application/json

# {
#   "email"   : "test_7@email.com",
#   "password": "123456" 
# }

### log Out 
POST http://localhost:3000/users/signout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZjYjBjZGEyLWJlMGEtNDhmYy1hOWVmLTQyOGFmNDljOWYzZSIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3MjU4ODU0NjYsImV4cCI6MTcyNTg4OTA2Nn0.HNFgS5Sh-5ZvYCcsKKYcd_DwZaABuwe3rcGPj7MSsOw


### Get all users
GET http://localhost:3000/users

### Get user by username
GET http://localhost:3000/users/admin

### Get Current user
GET http://localhost:3000/users/current
